CREATE DATABASE ACT1de1
GO

USE ACT1de1
GO

CREATE TABLE CARRERAS
(
	ID VARCHAR(4) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	FECHA_CREACION DATE NOT NULL CHECK(FECHA_CREACION < GETDATE()),
	EMAIL NVARCHAR(50) NOT NULL,
	NIVEL VARCHAR(15) CHECK(NIVEL = 'Diplomatura' or NIVEL = 'Pregrado' or NIVEL = 'Grado' or NIVEL = 'Posgrado'),
)
GO

CREATE TABLE MATERIAS
(
	IDMATERIA INT NOT NULL IDENTITY(1,1),
	IDCARRERA VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES CARRERAS(ID),
	NOMBREMATERIA NVARCHAR(50) NOT NULL,
	CARGAHORARIA INT NOT NULL CHECK(CARGAHORARIA>0),

	PRIMARY KEY(IDMATERIA),
)
GO

CREATE TABLE ALUMNOS
(
	LEGAJO INT NOT NULL IDENTITY(1000,1),
	IDCARRERA VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES CARRERAS(ID),
	APELLIDO NVARCHAR(50) NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	FCHA_NACIMIENTO DATE NOT NULL CHECK(FCHA_NACIMIENTO < GETDATE()),
	EMAIL NVARCHAR(100) NOT NULL UNIQUE,
	TELEFONO NVARCHAR(20),
	PRIMARY KEY(LEGAJO),
)
GO
